# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ]; # Don't know what it does, but the system breaks when removing it...

  # Networking
  networking.hostName = "dnix";

  # File Systems & Devices
  fileSystems."/" = {
      device = "/dev/disk/by-uuid/7cf25cd9-8d47-4fac-8371-4e9901d5b202";
      fsType = "ext4";
   };
  fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/E35B-9B7F";
      fsType = "vfat";
  };
  swapDevices = [ { device = "/dev/disk/by-uuid/0d61e6c7-90fa-48f5-8f75-a572010d7cb4"; } ];

  # Kernel Stuff
  boot = {
    kernelParams = [
      #"mem_sleep_default=sleep"
      #"acpi.ec_no_wakeup"
      #"tsc=unstable"
      #"trace_clock=local"
      #"tpm_tis.interrupts=0"
      "nowatchdog"
      #"amd_pstate.epp_enable=1"
      "mitigations=off"
      "cryptomgr.notests"
      "fbcon=nodefer" # removes the manufacturer logo, might be necessary for plymouth
      "loglevel=3"
    ];
    kernelModules = [ "kvm-intel" ];
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
  };

  # CPU
  hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
  #powerManagement.cpuFreqGovernor = lib.mkDefault "performance"; # Managed by cpupower kernel module & gui

  ## Hardware acceleration
  hardware.opengl.extraPackages = with pkgs; [
    intel-compute-runtime
    intel-media-driver
  ];
}