# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ]; # Don't know what it does, but the system breaks when removing it...

  # Networking
  networking.hostName = "dnix";

  # File Systems & Devices
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B6C7-8A7B";
    fsType = "vfat";
  };
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d1724ada-6dfe-45b7-8a0d-e65aa0127205";
    fsType = "ext4";
    options = [
      "lazytime"
      "commit=60"
    ];
  };
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/113a8b60-b786-4252-a9ca-e5c3b55cae0a";
    fsType = "ext4";
    options = [
      "noatime"
    ];
  };
  swapDevices = [
    {
      device = "/.swapfile";
      size = 32*1024;
      randomEncryption.enable = true;
    }
  ];


  # Kernel Stuff
  boot = {
    kernelParams = [
      #"mem_sleep_default=sleep"
      #"acpi.ec_no_wakeup"
      #"tsc=unstable"
      #"trace_clock=local"
      #"tpm_tis.interrupts=0"
      "nowatchdog"
      #"amd_pstate.epp_enable=1"
      "mitigations=off"
      "cryptomgr.notests"
      "fbcon=nodefer" # removes the manufacturer logo, might be necessary for plymouth
      "loglevel=3"
    ];
    kernelModules = [ "kvm-intel" ];
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
  };

  # CPU
  hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
  #powerManagement.cpuFreqGovernor = lib.mkDefault "performance"; # Managed by cpupower kernel module & gui

  ## Hardware acceleration
  hardware.opengl.extraPackages = with pkgs; [
    intel-compute-runtime
    intel-media-driver
  ];
}