# https://github.com/Mic92/sops-nix/issues/377#issuecomment-2926579189
# https://github.com/str4d/age-plugin-yubikey
keys:
  - &key-age-yubi age1yubikey1q0kwlt626takzr0z4vera4fjq504f789mj0e3rweehpwjt62pc73590y947
  # sops age yubikey stuff doesn't seem to work on nix-darwin...
  - &key-work age1nm0nrdwqvrznv2q88qt9tl3zdl7qe89v2u75pa4kwzaw6v5h99nq98vqzq
creation_rules:
  - path_regex: home-manager/secrets/(git\.yaml|keepassxc\.key)$
    key_groups:
      - age:
          - *key-work
          - *key-age-yubi
  - path_regex: home-manager/secrets/[^/]+\.(yaml|key|asc)$
    key_groups:
      - age:
          - *key-age-yubi
