# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ]; # Don't know what it does, but the system breaks when removing it...

  # File Systems & Devices
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/993E-935D";
    fsType = "vfat";
  };
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d3d26548-2e4e-49e6-a7a0-3d2c66b358b9";
    fsType = "ext4";
    options = [
      "lazytime"
      "commit=60"
    ];
  };
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/382b34eb-f14b-438c-b7e8-abdcbe1b23e8";
    fsType = "ext4";
    options = [
      "noatime"
    ];
  };
  swapDevices = [
    {
      device = "/swapfile";
      size = 32 * 1024;
      #randomEncryption.enable = true; # "Don’t try to hibernate when you have at least one swap partition with this option enabled!"
      discardPolicy = "both"; # randomEncryption.allowDiscards defaults to false
      #priority = -1; # always is -2, probably because it's a file (Linux man page claims range -1 to 32767 allowed...)
    }
  ];


  # Kernel Stuff
  boot = {
    extraModulePackages = with config.boot.kernelPackages; [
      system76-scheduler
      perf
      turbostat
      cpupower
    ];

    kernelParams = [
      "nowatchdog"
      "mitigations=off"
      "cryptomgr.notests"
      "fbcon=nodefer" # removes the manufacturer logo, might be necessary for plymouth
      "loglevel=3"
    ];
    kernelModules = [ "kvm-intel" ];
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
  };

  # CPU
  hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
  #powerManagement.cpuFreqGovernor = lib.mkDefault "performance"; # Managed by cpupower kernel module & gui

  # Hardware acceleration
  hardware.opengl.extraPackages = with pkgs; [
    intel-compute-runtime
    intel-media-driver
  ];
}
