# https://github.com/Mic92/sops-nix/issues/377#issuecomment-2926579189
# https://github.com/str4d/age-plugin-yubikey
keys:
  - &key-age-yubi age1yubikey1q0kwlt626takzr0z4vera4fjq504f789mj0e3rweehpwjt62pc73590y947
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|key|asc)$
    key_groups:
      - age:
          - *key-age-yubi
